services:
  prefect:
    image: prefecthq/prefect:2-latest
    ports:
      - "4200:4200"
    environment:
      PREFECT_LOGGING_LEVEL: debug
    command:
      - prefect
      - server
      - start
      - --host
      - "0.0.0.0"
      - --port
      - "4200"

  prometheus-exporter:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      PREFECT_API_URL: http://prefect:4200/api

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
