---
services:
  prefect:
    image: prefecthq/prefect:3-latest
    ports:
      - "4200:4200"
    environment:
      PREFECT_LOGGING_LEVEL: debug
      # PREFECT_SERVER_API_AUTH_STRING: ""
      # PREFECT_SERVER_API_CSRF_PROTECTION_ENABLED: "True"
      # PREFECT_SERVER_CSRF_PROTECTION_ENABLED: "True"
    command:
      - prefect
      - server
      - start
      - --host
      - "0.0.0.0"
      - --port
      - "4200"
    healthcheck:
      test: ["CMD-SHELL", "prefect version"]

  prometheus-exporter:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      PREFECT_API_URL: http://prefect:4200/api
      # PREFECT_API_AUTH_STRING: ""
      # PREFECT_CSRF_ENABLED: "True"
    depends_on:
      prefect:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    volumes:
      # https://grafana.com/docs/grafana/latest/administration/provisioning/
      - ./grafana-config/provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/etc/grafana/dashboards:ro
    depends_on:
      - prometheus
