global:
  scrape_interval: 5s
  external_labels:
    monitor: my-monitor
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: ceph-exporter
    static_configs:
      - targets: ['prometheus-exporter:8000']
