name: Bug report
description: Create a bug report
title: "Bug title"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: Please be cautious with the sensitive information/logs while filing the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug a clear and concise description of what the bug is.
    validations:
      required: true

  - type: input
    id: application-name
    attributes:
      label: Application name
      description: Enter the name of the application where you encountered this bug.
    validations:
      required: true

  - type: input
    id: application-version
    attributes:
      label: Application version
      description: Enter the version of the application that you encountered this bug.
    validations:
      required: true

  - type: textarea
    id: explain-bug
    attributes:
      label: Explain bug
      description: Explain what happened.
    validations:
      required: false

  - type: textarea
    id: expected-result
    attributes:
      label: What you expected to happen?
      description: Enter what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: reproduce-bug
    attributes:
      label: How to reproduce it?
      description: Explain step-by-step if is possible.
    validations:
      required: false

  - type: textarea
    id: more-info
    attributes:
      label: More info
    validations:
      required: false
