---
name: Build and Publish prometheus-prefect-exporter Image

"on":
  push:
    tags:
      - '*'

permissions: {}

jobs:
  build_push_exporter:
    permissions:
      # required to read from the repo
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: prefecthq/prometheus-prefect-exporter
          flavor: latest=true
          tags: |
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.title=prometheus-prefect-exporter
            org.opencontainers.image.description=Prometheus Prefect Exporter image
            org.opencontainers.image.vendor=PrefectHQ

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
          pull: true
          provenance: false
