---
name: Tests

"on":
  pull_request: {}
  push:
    branches:
      - main

permissions: {}

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run pytest
        run: pytest
